package it.polimi.ingsw.server.model.godPowers.fx;

public enum GodFX {
    ADD_BUILD_BEFORE_IF_NOT_MOVE_UP,
    ADD_BUILD_NOT_EDGE,
    ADD_BUILD_NOT_SAME_BOX,
    ADD_BUILD_ON_SAME_BOX,
    ADD_MOVE_NOT_STARTING_BOX,
    ADD_THREE_BUILDS_TO_UNMOVED_WORKER,
    BUILD_DOME_EVERYWHERE,
    BUILD_UNDER_YOURSELF,
    DO_NOTHING,
    OPPONENTS_CANT_MOVE_UP_IF_PLAYER_MOVES_UP,
    PUSH_ADJACENT_OPPONENT,
    REMOVE_ADJACENT_BLOCK,
    SWAP
}
