package it.polimi.ingsw.network;

public enum CommunicationProtocol {
    BUILDS, CARD, DECK, DESTINATIONS, GODPOWER, HI, MAP, MATCHTYPE, RECEIVED, STARTPOSITION, UNDO, USERNAME, UNIQUEUSERNAME, WORKER
}