package it.polimi.ingsw.network;

public enum CommunicationProtocol {
    BUILD,
    CARD,
    COUNTDOWN,
    CURRENT_PLAYER,
    DECK,
    DESTINATION,
    EMPTY,
    GOD_POWER,
    HI,
    INVALID,
    LOSER,
    MAP,
    MATCH_START,
    MATCH_STORY,
    MATCH_TYPE,
    MY_PLAYER,
    OPPONENTS,
    PING,
    PONG,
    QUIT,
    RECEIVED,
    REMOVAL,
    START_POSITION,
    TIMEOUT,
    UNDO,
    USERNAME,
    UNIQUE_USERNAME,
    WAIT_FOR_PLAYERS,
    WINNER,
    WORKER
}